baseURL = 'https://nafsiya.netlify.app/'
languageCode = 'en-us'
title = 'Nafsiya wellbeing Clinic'
theme = "ga-hugo-theme"

[params]
  assets = [
    "css/main.css"
  ]


[frontmatter]
home = "homepage"
contact = "contact"